import type { INodeProperties } from 'n8n-workflow';
import { blockchainOptions, networkOptions } from '../../transport/blockchainConstants';
import {
	MANAGE_BLOCKCHAINS,
	MANAGE_NETWORKS,
	MANAGE_ACTIVATE_DELETE_NETWORKS,
	EVM_STATISTICS_BLOCKCHAINS,
	EVM_STATISTICS_NETWORKS,
	EVM_TRANSACTIONS_BLOCKCHAINS,
	EVM_TRANSACTIONS_NETWORKS,
	EVM_TOKENS_TRANSFERS_BLOCKCHAINS,
	EVM_TOKENS_TRANSFERS_NETWORKS,
	EVM_INTERNAL_TRANSACTIONS_BLOCKCHAINS,
	EVM_INTERNAL_TRANSACTIONS_NETWORKS,
	EVM_TOKENS_BLOCKCHAINS,
	EVM_TOKENS_NETWORKS,
	UTXO_STATISTICS_BLOCKCHAINS,
	UTXO_STATISTICS_NETWORKS,
	UTXO_TRANSACTIONS_BLOCKCHAINS,
	UTXO_TRANSACTIONS_NETWORKS,
	UTXO_UNSPENT_OUTPUTS_BLOCKCHAINS,
	UTXO_UNSPENT_OUTPUTS_NETWORKS,
} from './blockchainEnums';

export const addressHistoryOperations: INodeProperties[] = [
	{
		displayName: 'Blockchain Type',
		name: 'blockchainType',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['addressHistory'] } },
		options: [
			{ name: 'Management (Sync/Activate/Delete)', value: 'management' },
			{ name: 'EVM', value: 'evm' },
			{ name: 'UTXO', value: 'utxo' },
		],
		default: 'management',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['addressHistory'] } },
		options: [
			{ name: 'Sync Address', value: 'syncAddress', description: 'Sync an address for full history tracking (Management)', action: 'Sync address for history tracking' },
			{ name: 'List Synced Addresses', value: 'listSyncedAddresses', description: 'List all synced addresses (Management)', action: 'List all synced addresses' },
			{ name: 'Activate Address', value: 'activateAddress', description: 'Activate a previously deactivated address sync (Management)', action: 'Activate an address sync' },
			{ name: 'Delete Address', value: 'deleteAddress', description: 'Delete an address sync (Management)', action: 'Delete an address sync' },
			{ name: 'Get Statistics', value: 'getStatistics', description: 'Get address statistics (EVM: Ethereum/Ethereum Classic only, UTXO: BTC/BCH only)', action: 'Get address history statistics' },
			{ name: 'List Transactions', value: 'listTransactions', description: 'List full transaction history for an address (EVM/UTXO)', action: 'List full transaction history for an address' },
			{ name: 'List Token Transfers', value: 'listTokenTransfers', description: 'List full token transfer history (EVM only)', action: 'List full token transfer history' },
			{ name: 'List Internal Transactions', value: 'listInternalTransactions', description: 'List full internal transaction history (EVM only)', action: 'List full internal transaction history' },
			{ name: 'List Tokens', value: 'listTokens', description: 'List all tokens held by address (EVM only)', action: 'List all tokens held by an address' },
			{ name: 'List Unspent Outputs', value: 'listUnspentOutputs', description: 'List unspent transaction outputs — UTXOs (UTXO only)', action: 'List unspent transaction outputs (UTXOs)' },
		],
		default: 'syncAddress',
	},
];

/**
 * Blockchain/network dropdowns are scoped per operation (not just per blockchainType) because the
 * spec's support varies by operation on the same resource — e.g. EVM getStatistics supports only
 * 2 chains while listTransactions supports 5. See ./blockchainEnums.ts for the source enums.
 */
export const addressHistoryFields: INodeProperties[] = [
	// Blockchain/Network (Management)
	{
		displayName: 'Blockchain',
		name: 'blockchain',
		type: 'options',
		required: true,
		default: 'bitcoin',
		options: blockchainOptions(MANAGE_BLOCKCHAINS),
		displayOptions: { show: { resource: ['addressHistory'], blockchainType: ['management'] } },
	},
	{
		displayName: 'Network',
		name: 'network',
		type: 'options',
		required: true,
		default: 'mainnet',
		options: networkOptions(MANAGE_NETWORKS),
		displayOptions: {
			show: {
				resource: ['addressHistory'],
				blockchainType: ['management'],
				operation: ['syncAddress', 'listSyncedAddresses'],
			},
		},
	},
	{
		displayName: 'Network',
		name: 'network',
		type: 'options',
		required: true,
		default: 'mainnet',
		description: 'Also accepts the deprecated Polygon testnet "mumbai" for activate/delete, per the spec',
		options: networkOptions(MANAGE_ACTIVATE_DELETE_NETWORKS),
		displayOptions: {
			show: {
				resource: ['addressHistory'],
				blockchainType: ['management'],
				operation: ['activateAddress', 'deleteAddress'],
			},
		},
	},
	// Blockchain/Network (EVM) — one pair per operation, enums differ per spec operation
	{
		displayName: 'Blockchain',
		name: 'blockchain',
		type: 'options',
		required: true,
		default: 'ethereum',
		options: blockchainOptions(EVM_STATISTICS_BLOCKCHAINS),
		displayOptions: { show: { resource: ['addressHistory'], blockchainType: ['evm'], operation: ['getStatistics'] } },
	},
	{
		displayName: 'Network',
		name: 'network',
		type: 'options',
		required: true,
		default: 'mainnet',
		options: networkOptions(EVM_STATISTICS_NETWORKS),
		displayOptions: { show: { resource: ['addressHistory'], blockchainType: ['evm'], operation: ['getStatistics'] } },
	},
	{
		displayName: 'Blockchain',
		name: 'blockchain',
		type: 'options',
		required: true,
		default: 'ethereum',
		options: blockchainOptions(EVM_TRANSACTIONS_BLOCKCHAINS),
		displayOptions: { show: { resource: ['addressHistory'], blockchainType: ['evm'], operation: ['listTransactions'] } },
	},
	{
		displayName: 'Network',
		name: 'network',
		type: 'options',
		required: true,
		default: 'mainnet',
		options: networkOptions(EVM_TRANSACTIONS_NETWORKS),
		displayOptions: { show: { resource: ['addressHistory'], blockchainType: ['evm'], operation: ['listTransactions'] } },
	},
	{
		displayName: 'Blockchain',
		name: 'blockchain',
		type: 'options',
		required: true,
		default: 'ethereum',
		options: blockchainOptions(EVM_TOKENS_TRANSFERS_BLOCKCHAINS),
		displayOptions: { show: { resource: ['addressHistory'], blockchainType: ['evm'], operation: ['listTokenTransfers'] } },
	},
	{
		displayName: 'Network',
		name: 'network',
		type: 'options',
		required: true,
		default: 'mainnet',
		options: networkOptions(EVM_TOKENS_TRANSFERS_NETWORKS),
		displayOptions: { show: { resource: ['addressHistory'], blockchainType: ['evm'], operation: ['listTokenTransfers'] } },
	},
	{
		displayName: 'Blockchain',
		name: 'blockchain',
		type: 'options',
		required: true,
		default: 'ethereum',
		options: blockchainOptions(EVM_INTERNAL_TRANSACTIONS_BLOCKCHAINS),
		displayOptions: { show: { resource: ['addressHistory'], blockchainType: ['evm'], operation: ['listInternalTransactions'] } },
	},
	{
		displayName: 'Network',
		name: 'network',
		type: 'options',
		required: true,
		default: 'mainnet',
		options: networkOptions(EVM_INTERNAL_TRANSACTIONS_NETWORKS),
		displayOptions: { show: { resource: ['addressHistory'], blockchainType: ['evm'], operation: ['listInternalTransactions'] } },
	},
	{
		displayName: 'Blockchain',
		name: 'blockchain',
		type: 'options',
		required: true,
		default: 'ethereum',
		options: blockchainOptions(EVM_TOKENS_BLOCKCHAINS),
		displayOptions: { show: { resource: ['addressHistory'], blockchainType: ['evm'], operation: ['listTokens'] } },
	},
	{
		displayName: 'Network',
		name: 'network',
		type: 'options',
		required: true,
		default: 'mainnet',
		options: networkOptions(EVM_TOKENS_NETWORKS),
		displayOptions: { show: { resource: ['addressHistory'], blockchainType: ['evm'], operation: ['listTokens'] } },
	},
	// Blockchain/Network (UTXO) — one pair per operation, enums differ per spec operation
	{
		displayName: 'Blockchain',
		name: 'blockchain',
		type: 'options',
		required: true,
		default: 'bitcoin',
		options: blockchainOptions(UTXO_STATISTICS_BLOCKCHAINS),
		displayOptions: { show: { resource: ['addressHistory'], blockchainType: ['utxo'], operation: ['getStatistics'] } },
	},
	{
		displayName: 'Network',
		name: 'network',
		type: 'options',
		required: true,
		default: 'mainnet',
		options: networkOptions(UTXO_STATISTICS_NETWORKS),
		displayOptions: { show: { resource: ['addressHistory'], blockchainType: ['utxo'], operation: ['getStatistics'] } },
	},
	{
		displayName: 'Blockchain',
		name: 'blockchain',
		type: 'options',
		required: true,
		default: 'bitcoin',
		options: blockchainOptions(UTXO_TRANSACTIONS_BLOCKCHAINS),
		displayOptions: { show: { resource: ['addressHistory'], blockchainType: ['utxo'], operation: ['listTransactions'] } },
	},
	{
		displayName: 'Network',
		name: 'network',
		type: 'options',
		required: true,
		default: 'mainnet',
		options: networkOptions(UTXO_TRANSACTIONS_NETWORKS),
		displayOptions: { show: { resource: ['addressHistory'], blockchainType: ['utxo'], operation: ['listTransactions'] } },
	},
	{
		displayName: 'Blockchain',
		name: 'blockchain',
		type: 'options',
		required: true,
		default: 'bitcoin',
		options: blockchainOptions(UTXO_UNSPENT_OUTPUTS_BLOCKCHAINS),
		displayOptions: { show: { resource: ['addressHistory'], blockchainType: ['utxo'], operation: ['listUnspentOutputs'] } },
	},
	{
		displayName: 'Network',
		name: 'network',
		type: 'options',
		required: true,
		default: 'mainnet',
		options: networkOptions(UTXO_UNSPENT_OUTPUTS_NETWORKS),
		displayOptions: { show: { resource: ['addressHistory'], blockchainType: ['utxo'], operation: ['listUnspentOutputs'] } },
	},
	// Address (not needed for listSyncedAddresses)
	{
		displayName: 'Address',
		name: 'address',
		type: 'string',
		required: true,
		default: '',
		description: 'The blockchain address',
		displayOptions: {
			show: { resource: ['addressHistory'] },
			hide: { operation: ['listSyncedAddresses'] },
		},
	},
	// Pagination
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		displayOptions: {
			show: {
				resource: ['addressHistory'],
				operation: ['listSyncedAddresses', 'listTransactions', 'listTokenTransfers', 'listInternalTransactions', 'listTokens', 'listUnspentOutputs'],
			},
		},
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1, maxValue: 200 },
		default: 50,
		description: 'Max number of results to return',
		displayOptions: {
			show: {
				resource: ['addressHistory'],
				operation: ['listSyncedAddresses', 'listTransactions', 'listTokenTransfers', 'listInternalTransactions', 'listTokens', 'listUnspentOutputs'],
				returnAll: [false],
			},
		},
	},
];
